//import java.JavaApplication.Button;
import static com.sun.java.accessibility.util.AWTEventMonitor.addActionListener;
import java.awt.event.*;  
import javax.swing.*;    
public class JavaApplication {
    public static int p,q;
    JFrame f= new JFrame("Example");
    public JavaApplication() {  
        JFrame frame=new JFrame("Button Example");   
        Button button1=new Button();
        frame.add(button1.b0);
        frame.add(button1.b1);
        frame.add(button1.b2);
        frame.add(button1.b3);
        frame.add(button1.b4);
        frame.add(button1.b5);
        frame.add(button1.b6);
        frame.add(button1.b7);
        frame.add(button1.b8);
        frame.add(button1.b9);
        frame.add(button1.b10);
        frame.add(button1.b11);
        frame.add(button1.b12);
        frame.add(button1.b13);
        frame.add(button1.b14);
        frame.add(button1.b15);
        frame.add(button1.b16);
        frame.add(button1.b17);
        frame.add(button1.b18);
        frame.add(button1.b19);
        frame.add(button1.b20);
        frame.add(button1.b21);
        frame.add(button1.b22);
        frame.add(button1.b23);
        frame.add(button1.b24);
        frame.add(button1.b25);
        frame.add(button1.b26);
        frame.add(button1.b27);
        frame.add(button1.b28);
        frame.add(button1.b29);
        frame.add(button1.b30);
        frame.add(button1.b31);
        frame.add(button1.b32);
        frame.add(button1.b33);
        frame.add(button1.b34);
        frame.add(button1.b35);
        frame.add(button1.b36);
        frame.add(button1.b37);
        frame.add(button1.b38);
        frame.add(button1.b39);
        frame.add(button1.b40);
        frame.add(button1.b41);
        frame.add(button1.b42);
        frame.add(button1.b43);
        frame.add(button1.b44);
        frame.add(button1.b45);
        frame.add(button1.b46);
        frame.add(button1.b47);
        frame.add(button1.b48);
        frame.add(button1.b49);
        frame.add(button1.b50);
        frame.add(button1.b51);
        frame.add(button1.b52);
        frame.add(button1.b53);
        frame.add(button1.b54);
        frame.add(button1.b55);
        frame.add(button1.b56);
        frame.add(button1.b57);
        frame.add(button1.b58);
        frame.add(button1.b59);
        frame.add(button1.b60);
        frame.add(button1.b61);
        frame.add(button1.b62);
        frame.add(button1.b63);

        
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 700);
        frame.setLayout(null);
        frame.setVisible(true);
    }
}